### PR TITLE
pull in upstream patch cepc/CEPCSW#65

### PR DESCRIPTION
**Pull request by joequant**
This is a workaround for the fix to cepc/CEPCSW#65

### CODE REVIEW

**Comment by mirguest** [comment]
Hi @joequant ,
Your Pull Request https://github.com/cepc/CEPCSW/pull/65 is merged. 
Thank you very much.
Tao

**Comment by vvolkl** [comment]
Thanks @joequant. since this is in CEPSW master, can I close?

**Comment by joequant** [comment]
Yes.  Please close.

在 2020年10月20日 週二 20:53，vvolkl <notifications@github.com> 寫道：

**Comment by vvolkl** [comment]
(Apologies, I merged by accident and reverted it already)

**Pull request merged**
