### PR TITLE
Add new spack config files

### LINKED ISSUE #42: Need to add python 3.7 for Gaudi
need to add the following to key4hep-stack for gaudi

    # gaudi needs 3.7.99
    depends_on('python@:3.7.99')

Right now the dependencies I have for key4hep-stack

    # be explicit to avoid concretizer errors
    depends_on('root cxxstd=17 +root7 +ssl')
    depends_on('boost +python')
    depends_on('clhep cxxstd=17')
    # gaudi needs 3.7.99
    depends_on('python@:3.7.99')

### PR DESCRIPTION
**Pull request by vvolkl**
... and delete the ones for the lcg releases.

EDIT: Fixes #42

### CODE REVIEW

**Comment by andresailer** [comment]
How or when are these config packages used? Just automatically, or do they need to be copied to, e.g., `~/.spack`?

**Comment by vvolkl** [comment]
The `packages.yaml` is a convenience in order not to have to manually resolve some concretizer errors and to set some better variants for the build - which avoids installing some unneeded dependencies and  reduces the build time.

Yes, the config file has to be copied to a proper directory. There are a couple of locations that spack searches for config files, see https://spack.readthedocs.io/en/latest/configuration.html (I added the link to the readme too) I think we were discussing  providing a "pre-configured" spack, which can include these config files in the right place, but in this repository we can only provide them, the user has to do the setup.

**Comment by andresailer** [comment]
Thanks for the link to the documentation!
One can do `--custom-scope k4-spack/config/path/to` or (`-C`) with the spack command to avoid copying.
https://spack.readthedocs.io/en/latest/configuration.html#custom-scopes
If a config file is required, it could be added as a flag to the instructions.

**Comment by vvolkl** [comment]
Or one can copy to avoid add typing command line arguments :) Seems to be a matter of taste.
Added the line to the setup instructions: https://github.com/key4hep/key4hep-doc/commit/912f2f1f4cdabe1b39aba5b994a9dfbc3814898c

**Comment by andresailer** [comment]
But if you switch the configs a lot you never know what the current state of the config is, and then using a well defined set of files is much clearer and reproducible.
It also allows one to just "copy and paste" the commands and not worry about the user having some spack config which is overwritten permanently by copying the files.

**Pull request merged**
